/* Query 1: Discount Band Profitability Analysis
   How do different discount bands impact sales, profit, and profit margins?
*/

SELECT
    CASE
        WHEN Order_Item_Discount_Rate = 0 THEN 'No Discount'
        WHEN Order_Item_Discount_Rate <= 0.10 THEN '0–10%'
        WHEN Order_Item_Discount_Rate <= 0.20 THEN '10–20%'
        ELSE '20%+'
    END AS Discount_Band,

    COUNT(*) AS Total_Orders,

    ROUND(AVG(Sales),2) AS Avg_Sales,

    ROUND(AVG(Order_Profit_Per_Order),2) AS Avg_Profit,

    ROUND(AVG(Profit_Margin),2) AS Avg_Profit_Margin

FROM supply_chain_cleaned

GROUP BY
CASE
    WHEN Order_Item_Discount_Rate = 0 THEN 'No Discount'
    WHEN Order_Item_Discount_Rate <= 0.10 THEN '0–10%'
    WHEN Order_Item_Discount_Rate <= 0.20 THEN '10–20%'
    ELSE '20%+'
END

ORDER BY Avg_Profit;

/* Query 2:
   How much revenue is generated by repeat customers compared to first-time customers?
   */

   WITH Customer_Summary AS
(
    SELECT
        Customer_Id,
        COUNT(Order_Id) AS Total_Orders,
        SUM(Sales) AS Revenue
    FROM supply_chain_cleaned
    GROUP BY Customer_Id
)

SELECT
    CASE
        WHEN Total_Orders > 1 THEN 'Repeat Customer'
        ELSE 'First-Time Customer'
    END AS Customer_Type,

    COUNT(Customer_Id) AS Total_Customers,

    ROUND(SUM(Revenue),2) AS Total_Revenue,

    ROUND(AVG(Revenue),2) AS Avg_Revenue_Per_Customer

FROM Customer_Summary

GROUP BY
CASE
    WHEN Total_Orders > 1 THEN 'Repeat Customer'
    ELSE 'First-Time Customer'
END

ORDER BY Total_Revenue DESC;


/* Query 3: Revenue at Risk by Region
   Which regions have the highest revenue exposed to delivery risk?
*/

SELECT
    TOP 5 Order_Region,

    COUNT(*) AS Total_Orders,

    ROUND(SUM(Revenue_at_Risk),2) AS Total_Revenue_At_Risk,

    ROUND(AVG(Revenue_at_Risk),2) AS Avg_Revenue_At_Risk,

    ROUND(SUM(Sales),2) AS Total_Sales

FROM supply_chain_cleaned

GROUP BY Order_Region

ORDER BY Total_Revenue_At_Risk DESC;




/* Query 4: Top 5 Most Profitable Categories
   Which product categories generate the highest overall profit?
*/

SELECT TOP 5
    Category_Name,
    ROUND(SUM(Order_Profit_Per_Order),2) AS Total_Profit,
    ROUND(SUM(Sales),2) AS Total_Sales,
    COUNT(*) AS Total_Orders
FROM supply_chain_cleaned
GROUP BY Category_Name
ORDER BY Total_Profit DESC;




/* Query 5: Category-wise Delay Rate Analysis
   Which product categories experience the highest delayed delivery rate?
*/

SELECT 
   TOP 5 Category_Name,
    COUNT(*) AS Total_Orders,
    SUM(CASE WHEN Delay_Days > 0 THEN 1 ELSE 0 END) AS Delayed_Orders,
    ROUND(
        100.0 * SUM(CASE WHEN Delay_Days > 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS Delay_Rate
FROM supply_chain_cleaned
GROUP BY Category_Name
HAVING COUNT(*) >= 1000
ORDER BY Delay_Rate DESC;




/* Query 6: Revenue per Customer by Region
   Which regions have a large customer base but generate lower revenue per customer, indicating opportunities for revenue growth?
*/

SELECT
    TOP 5
    Order_Region,

    COUNT(DISTINCT Customer_Id) AS Total_Customers,

    ROUND(SUM(Sales),2) AS Total_Sales,

    ROUND(
        SUM(Sales) * 1.0 / COUNT(DISTINCT Customer_Id),
        2
    ) AS Revenue_Per_Customer,

    ROUND(SUM(Order_Profit_Per_Order),2) AS Total_Profit

FROM supply_chain_cleaned

GROUP BY Order_Region

HAVING COUNT(DISTINCT Customer_Id) >= 100

ORDER BY Revenue_Per_Customer ASC;




/* Query 7: Department-wise Sales & Profit Analysis
   How do different departments perform in terms of sales and profitability?
*/

SELECT
    Department_Name,

    ROUND(SUM(Sales),2) AS Total_Sales,

    ROUND(SUM(Order_Profit_Per_Order),2) AS Total_Profit,

    COUNT(*) AS Total_Orders

FROM supply_chain_cleaned

GROUP BY Department_Name

ORDER BY Total_Profit DESC;




/* Query 8: High Revenue but Loss-Making Customers
   Which customers generate high revenue despite resulting in an overall loss?
*/

SELECT TOP 10
    Customer_Id,

    COUNT(*) AS Total_Orders,

    ROUND(SUM(Sales),2) AS Total_Sales,

    ROUND(SUM(Order_Profit_Per_Order),2) AS Total_Profit,

    ROUND(AVG(Order_Item_Discount_Rate)*100,2) AS Avg_Discount

FROM supply_chain_cleaned

GROUP BY Customer_Id

HAVING SUM(Order_Profit_Per_Order) < 0

ORDER BY Total_Sales DESC;




/* Query 9: High-Performing Markets with Delivery Challenges
   Which top-performing markets generate the highest sales while experiencing the highest number of delayed orders?
*/

SELECT TOP 5
    Market,

    COUNT(*) AS Total_Orders,

    ROUND(SUM(Sales),2) AS Total_Sales,

    ROUND(SUM(Order_Profit_Per_Order),2) AS Total_Profit,

    SUM(CASE
            WHEN Late_delivery_risk = 1 THEN 1
            ELSE 0
        END) AS Delayed_Orders

FROM supply_chain_cleaned

GROUP BY Market

ORDER BY Total_Sales DESC;



/* Query 10: Top Revenue Contributing Categories
   Which product categories contribute the highest share of overall revenue?
*/

SELECT TOP 5
    Category_Name,

    ROUND(SUM(Sales),2) AS Total_Sales,

    COUNT(*) AS Total_Orders,

    ROUND(
        SUM(Sales) * 100.0 /
        (SELECT SUM(Sales) FROM supply_chain_cleaned),
        2
    ) AS Revenue_Contribution_Percent

FROM supply_chain_cleaned

GROUP BY Category_Name

ORDER BY Total_Sales DESC;



/* Query 11: Order Status Distribution Analysis
   How is revenue distributed across different business order statuses?
*/

SELECT
    CASE
        WHEN Order_Status IN ('COMPLETE','CLOSED')
            THEN 'Completed'

        WHEN Order_Status IN ('PROCESSING','PENDING','ON_HOLD')
            THEN 'Operational Pipeline'

        WHEN Order_Status='PENDING_PAYMENT'
            THEN 'Pending Payment'

        WHEN Order_Status='SUSPECTED_FRAUD'
            THEN 'Fraud Risk'

        WHEN Order_Status='CANCELED'
            THEN 'Cancelled'

        ELSE 'Others'
    END AS Business_Status,

    COUNT(*) AS Total_Orders,

    ROUND(SUM(Sales),2) AS Revenue,

    ROUND(
        SUM(Sales)*100.0/
        (SELECT SUM(Sales) FROM supply_chain_cleaned),2
    ) AS Revenue_Percentage

FROM supply_chain_cleaned

GROUP BY
CASE
        WHEN Order_Status IN ('COMPLETE','CLOSED')
            THEN 'Completed'

        WHEN Order_Status IN ('PROCESSING','PENDING','ON_HOLD')
            THEN 'Operational Pipeline'

        WHEN Order_Status='PENDING_PAYMENT'
            THEN 'Pending Payment'

        WHEN Order_Status='SUSPECTED_FRAUD'
            THEN 'Fraud Risk'

        WHEN Order_Status='CANCELED'
            THEN 'Cancelled'

        ELSE 'Others'
END

ORDER BY Revenue DESC;




/* Query 12: Fraud Exposure Analysis
   Which payment methods and markets contribute the highest financial fraud exposure?
*/

SELECT
    Type AS Payment_Type,
    Market,
    COUNT(Order_Id) AS Fraud_Order_Count,
    ROUND(SUM(Sales),2) AS Fraud_Exposure_Value,
    ROUND(AVG(Sales),2) AS Avg_Order_Value,
    ROUND(AVG(Order_Item_Discount_Rate)*100,2) AS Avg_Discount_Percentage
FROM supply_chain_cleaned
WHERE Order_Status = 'SUSPECTED_FRAUD'
GROUP BY Type, Market
ORDER BY Fraud_Exposure_Value DESC;



/* Query 13: Revenue Lost Due to Failed Orders
   Which product categories experience the highest revenue loss due to cancelled or incomplete orders?
*/

SELECT
    Category_Name,
    SUM(
        CASE
            WHEN Order_Status IN ('CANCELED','PENDING_PAYMENT','PAYMENT_REVIEW')
            THEN Sales
            ELSE 0
        END
    ) AS Lost_Revenue,

    SUM(Sales) AS Total_Revenue,

    ROUND(
        SUM(
            CASE
                WHEN Order_Status IN ('CANCELED','PENDING_PAYMENT','PAYMENT_REVIEW')
                THEN Sales
                ELSE 0
            END
        ) * 100.0 /
        NULLIF(SUM(Sales),0),
        2
    ) AS Revenue_Loss_Percentage

FROM supply_chain_cleaned
GROUP BY Category_Name
ORDER BY Revenue_Loss_Percentage DESC;




/* Query 14: High-Value At-Risk Customers
   Which high-value customers are at risk due to frequent late deliveries?
*/

WITH Customer_Summary AS
(
    SELECT
        Customer_Id,
        COUNT(Order_Id) AS Total_Orders,
        SUM(Sales) AS Total_Revenue,
        AVG(Sales) AS Avg_Order_Value,
        SUM(Order_Profit_Per_Order) AS Total_Profit,
        SUM(CASE
                WHEN Late_delivery_risk = 1 THEN 1
                ELSE 0
            END) AS Late_Orders
    FROM supply_chain_cleaned
    GROUP BY Customer_Id
)

SELECT TOP 20
    Customer_Id,
    Total_Orders,
    ROUND(Total_Revenue,2) AS Total_Revenue,
    ROUND(Avg_Order_Value,2) AS Avg_Order_Value,
    ROUND(Total_Profit,2) AS Total_Profit,
    Late_Orders,
    ROUND(
        Late_Orders * 100.0 /
        NULLIF(Total_Orders,0),
        2
    ) AS Late_Order_Percentage
FROM Customer_Summary
ORDER BY Total_Revenue DESC;




/* Query 15:
   How is revenue distributed across customer groups based on the Pareto principle?
*/

WITH CustomerRevenue AS
(
    SELECT
        Customer_Id,
        SUM(Sales) AS Revenue
    FROM supply_chain_cleaned
    GROUP BY Customer_Id
),

RankedCustomers AS
(
    SELECT
        Customer_Id,
        Revenue,
        NTILE(5) OVER (ORDER BY Revenue DESC) AS Revenue_Group
    FROM CustomerRevenue
),

Pareto AS
(
    SELECT
        Revenue_Group,
        COUNT(*) AS Customers,
        SUM(Revenue) AS Revenue
    FROM RankedCustomers
    GROUP BY Revenue_Group
)

SELECT
CASE Revenue_Group
    WHEN 1 THEN 'Top 20%'
    WHEN 2 THEN 'Next 20%'
    WHEN 3 THEN 'Middle 20%'
    WHEN 4 THEN 'Lower 20%'
    WHEN 5 THEN 'Bottom 20%'
END AS Customer_Group,

Customers,

ROUND(Revenue,2) AS Revenue,

ROUND(
    Revenue * 100.0 /
    SUM(Revenue) OVER(),
    2
) AS Revenue_Percentage

FROM Pareto
ORDER BY Revenue_Group;




/* Query 16: Revenue Recovery Opportunity Analysis
   Which markets offer the greatest revenue recovery opportunity by reducing late deliveries?
*/

SELECT

    Market,

    COUNT(Order_Id) AS Total_Orders,

    SUM(CASE
            WHEN Late_delivery_risk = 1
            THEN 1
            ELSE 0
        END) AS Late_Orders,

    ROUND(
        SUM(CASE
                WHEN Late_delivery_risk = 1
                THEN Sales
                ELSE 0
            END),
        2
    ) AS Revenue_At_Risk,

    ROUND(
        SUM(CASE
                WHEN Late_delivery_risk = 1
                THEN Sales
                ELSE 0
            END) * 0.10,
        2
    ) AS Recoverable_Revenue

FROM supply_chain_cleaned

GROUP BY Market

ORDER BY Recoverable_Revenue DESC;




/* Query 17: Revenue Impact of High-Value Orders
   Do high-value orders face a greater risk of delivery delays?
*/

SELECT
    CASE
        WHEN Sales >= 1500 THEN 'High Revenue Orders'
        ELSE 'Other Orders'
    END AS Order_Type,

    COUNT(*) AS Total_Orders,

    SUM(CASE WHEN Delay_Days > 0 THEN 1 ELSE 0 END) AS Delayed_Orders,

    ROUND(
        100.0 * SUM(CASE WHEN Delay_Days > 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS Delay_Rate,

    ROUND(SUM(Sales),2) AS Total_Revenue

FROM supply_chain_cleaned

GROUP BY
    CASE
        WHEN Sales >= 1500 THEN 'High Revenue Orders'
        ELSE 'Other Orders'
    END;



